name: Trigger Release

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Build version'
        required: true

jobs:
  invoke_webhook:
    runs-on: ubuntu-latest
    steps:
    - name: Invoke Webhook
      uses: ClearScore/workflow-webhook@v2
      env:
        webhook_url: "https://github.spinnaker.cicd.clearscore.io/github-webhook/"
        webhook_secret: "secret"
        verbose: true
        data: '{"version": "${{ github.event.inputs.name }}"}'
